### ISSUE TITLE
Use newer GL version...

### ISSUE THREAD

**Issue by eeucalyptus** [eeucalyptus/eeDA#12]
We use the OpenGL binding of PyQt5. This supports OpenGL 2 (2.1 seems to work as well) as the newest GL version (as stated [here](http://pyqt.sourceforge.net/Docs/PyQt5/opengl.html)). I found some projects using PyOpenGL which works with OpenGL up to 4.5. PyOpenGL seems to work perfectly with PyQt5 and the calls would only change from
```python
self.gl.glEnable(self.gl.GL_TEXTURE_2D)
```
to
```python
gl.glEnable(gl.GL_TEXTURE_2D)
```
Only the initialization and the imports might change slightly... Unfortunately, I didn't find an option to force an older API version (like 2.1) in PyOpenGL, which might require to finish #11 first. 

Code example using this combination:
[https://stackoverflow.com/a/38766800](https://stackoverflow.com/a/38766800)

**Comment by Musicted** [comment]
Since compatibility with my machine (and, most likely, a whole subset of computers) is still unattainable, I'll take it upon myself to close this issue for now, to be re-opened at some later date.
