### ISSUE TITLE
pixel perfect grid

### ISSUE THREAD

**Issue by eeucalyptus** [eeucalyptus/eeDA#7]
The grid looks a bit washed out. The objective is therefore to make the grid look sharp and clear, but not too obtusive... 
A close up screenshot (scaled up) is attached
![grid](https://user-images.githubusercontent.com/340901/30783569-568f06c6-a145-11e7-921f-c21cf22a3025.PNG)

**Comment by Musicted** [comment]
AA has been disabled for the grid's call list, remedying the issue.

**Comment by eeucalyptus** [comment]
This looks like so nice now... It makes me wanna shit rainbows!
