### ISSUE TITLE
Text rendering

### ISSUE THREAD

**Issue by eeucalyptus** [eeucalyptus/eeDA#9]
# Explaination
We need some kind of text rendering in gl. The most efficient way to do so seams to be rendering on a gl texture and then mapping this texture on a quad to determine the geometry.

# Specs:
- OpenType compatible (works with arbitrary ttf files)
- UTF-8 compatible (renders unicode strings in utf-8 encoding)
- New module in package "graphics" (e.g. "textrendering.py" or something...)
- architecture should include static font caching, to prevent loading the font over and over again (maybe using a module dict with all recently used fonts?)
- interfaceing: 
    - function call something like `tex = RenderText(fontPath="fonts/freesans.ttf", text="Hello World", textHeight, isBold=False, isItalic=False, isUnderlined=False, isOverlined=False)`
    - tex is then some representation for a gl-texture (is there a data type in pyqt5?)
    - tex can be used in the renderers and may be cached, such that the texture must only be re-rendered when it changes

# To start...
Some reading on that topic:
- [http://www.pythonware.com/products/pil/](http://www.pythonware.com/products/pil/)
- [https://github.com/fonttools/fonttools](https://github.com/fonttools/fonttools)
- [https://stackoverflow.com/questions/14915167/how-to-load-and-bind-a-texture-with-qts-opengl-classes](https://stackoverflow.com/questions/14915167/how-to-load-and-bind-a-texture-with-qts-opengl-classes) (although this just shows that it does not seem to be possible using just pyqt5 :P)

**Comment by eeucalyptus** [comment]
I think PIL would be a good choice to render the fonts. But the more important issue seems to be the conversion into a gl texture. [This module](https://gist.github.com/pwuertz/6507cb95562f1db6df84) creates a texture using numpy. Dunno if thats anything similar.

**Comment by Musicted** [comment]
I'll give [freetype-py](https://pypi.python.org/pypi/freetype-py/) a chance. It's a collection of [freetype ](https://www.freetype.org/index.html)bindings for python. freetype is distributed und a BSD-style license.
That'd entail rendering bitmaps in-situ, maybe in steps of a factor of 2 in size, whenever they're needed.
It should be pretty enough for now and easily enough implemented for me not to be pissed if we eventually replace it.

**Comment by eeucalyptus** [comment]
Fun fact on FreeType:
Apple used to hold some patents on font hinting and prevented their usage in FreeType until 2011 (expiration date). Nevertheless, FreeType was used in macOS and iOS, with the activated hinting features. I'm trying not to judge this, but I really find this interesting :D [source](https://opensource.googleblog.com/2013/05/got-cff.html?m=1)

**Comment by Musicted** [comment]
The branch is mergedso I think our work here is almost done.
